version: '3'

services:
 v2ray:
    image: easonsummer/ssrpanel-v2ray-docker:go
    restart: always
    ports:
      - "7781:7781" 
    dns:
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - ./v2ray/config.json:/usr/bin/v2ray/config.json
    logging:
      options:
        max-size: "10m"
        max-file: "3"
      
 caddy:
    image: abiosoft/caddy:0.11.0-no-stats
    restart: always
    environment:
      - ACME_AGREE=true
    links:
      - v2ray:v2ray
    ports:
      - "80:80"
      - "443:443" 
    volumes:
      - ./caddy/.caddy:/root/.caddy 
      - ./caddy/Caddyfile:/etc/Caddyfile
      - ./caddy/www:/srv/www

 ssrmu:
    image: easonsummer/ssrpanel-ssrmu
    restart: always
    network_mode: "host"
    volumes:
      - ./ssrmu/user-config.json:/root/shadowsocks/user-config.json
      - ./ssrmu/usermysql.json:/root/shadowsocks/usermysql.json
      - ./ssrmu/dns.conf:/root/shadowsocks/dns.conf
    command: python /root/shadowsocks/server.py
    logging:
      options:
        max-size: "10m"
        max-file: "3"
